### ISSUE TITLE
Beastmaster Hunter "Play Dead" & "Wake Up" issue!

### ISSUE THREAD

**Issue by DoubleHighC** [kodewdle/IconPacks#1]
Hi there

I have an issue when I play my BM Hunter!

When I use "Play Dead" on my pet normally the icon changes to "Wake Up" and I can wake up my pet again!
With the Icon Pack installed the icon doesn't change after using "Play Dead" to "Wake Up" and I also cannot use
the same button to wake up my pet again!

Tested it without the icon pack workes as intended but DOESN'T work as soon as I install the icon pack
and works again after I deinstalled the icon pack!

I used the Clean Icon Pack!

By the way really really nice ICONS! Thank you very much for your work! :-)

Have a nice day/night whatever it is right now at your location! :-D

Thank you in advance

**Comment by kodewdle** [comment]
the icon pack can't really choose which are shown. it just replaces the textures in the client with stylized ones
i guess they could mimic the icon for two abilities but i don't do that with any of them
