### ISSUE TITLE
Eternal Traveler's Hearthstone Icon missing

### ISSUE THREAD

**Issue by xorph** [kodewdle/IconPacks#3]
Is it possible to replace the icon for the "Eternal Traveler's Hearthstone" (ID: 172179)?

![image](https://user-images.githubusercontent.com/8446421/204135989-b38dfbef-bd8d-48ab-a944-e5c6de7fb068.png)

Best regards

**Comment by kodewdle** [comment]
probably not.  if it was an encrypted icon, we can't replace them with interface art.  that is, unless they change them later in the client (which they aren't known for doing).
