### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by MainX342** [kodewdle/IconPacks#4]
I downloaded the latest version for Retail (dark) to version “Retail 11.0.0.54311”, but it does not change the icons of Algari Healing Potion, Treacherous Transmitter, as well as other trinkets and some heroic talents (fatebound coins, deathstalker mark etc). Although the icons for these items were in earlier versions
![image](https://github.com/user-attachments/assets/58a2bcdc-cb7d-45c7-9b25-404afcab7d2a)

**Comment by kodewdle** [comment]
updated the packs 🌼
