### ISSUE TITLE
How can I make it work for 3.3.5a?

### ISSUE THREAD

**Issue by armchairrockstar1** [kodewdle/IconPacks#5]
This is a question rather than an issue but is it possible to make this work on a 3.3.5a client (for private servers?)

I tried Wrath-Dark version and didn't see any change in game.

**Comment by Macumbafeh** [comment]
Yeah it's because the format files are .tga for every classic packs except Stock and Clean version

@kodewdle could you add those pack with .blp format for it to work please?

Also an other request is it possible to make a Gloss version for Classic?

**Comment by armchairrockstar1** [comment]
Update: I converted all the .tga files to .blp successfully and it still doesn't work. Could it be about the folder structure or filenames being different for 3.3.5a?

**Comment by Soromeister** [comment]
Since this is fixed, mind if you close the issue @armchairrockstar1 ?
