### ISSUE TITLE
Missing Shaman Icons + Trinkets

### ISSUE THREAD

**Issue by Taleidan** [kodewdle/IconPacks#5]
Hi!

It appears that Thunderstrike Ward and Ancestral Swiftness for Elemental are missing with the current release

![image](https://github.com/user-attachments/assets/2a52ecde-4a48-4d80-bd2c-9135d12fb528)

As well as Surging Totem for Restoration

![image](https://github.com/user-attachments/assets/f8d959b5-83d5-4d37-aabd-0196fa944b1a)

These trinkets as well
![image](https://github.com/user-attachments/assets/9223685e-a889-48d0-b9ef-1541167da28e)
![image](https://github.com/user-attachments/assets/684caeb0-e0d4-4b10-a714-7447f88011e7)

Would it be possible to have these added as well?

Really appreciate all the work on these icon packs! :pray:

**Comment by kodewdle** [comment]
updated the packs 🌼
